spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #dialect: org.hibernate.dialect.MariaDBDialect
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MYSQL 설정
    url: jdbc:mysql://127.0.0.1:3307/dorundorun
    username: root
    password: 1234

      #    driver-class-name: org.mariadb.jdbc.Driver # MARIADB 설정
      #    url: jdbc:mariadb://localhost:3306/semo
      #    password: 1234
      #    username: root

    # H2 Setting Info (H2 Console에 접속하기 위한 설정정보 입력)
  #    h2:
  #      console:
  #      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
  #      path: /h2-console  # H2 Console의 Path
  #    # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
  #    datasource:
  #    driver-class-name: org.h2.Driver  # Database를 H2로 사용
  #    url: jdbc:h2:~/test  # H2 접속 정보
  #    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
  #    password:  # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)

  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.orm.jdbc.bind: trace