spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/doruntest
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
    database-platform: org.hibernate.dialect.MySQL8Dialect